=== theKevatron/Archive/XML/Lab 3/Case 2/mdpba.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
   New Perspectives on XML
   Tutorial 3
   Case Problem 2

   MDPBA schema
   Author: Kevin Morales
   Date: 9/17/2021 

   Filename:          mdpba.xsd
   Supporting Files:  mdpba.xml
 
-->      
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:attribute name="grade" type="gradeType" />
	<xs:attribute name="type" type="eType" />
	<xs:attribute name="old" type="oldType" />
	<xs:attribute name="source" type="srcType" />
	<xs:element name="city" type="xs:string" />
	<xs:element name="tune" type="xs:string" />
	
	<xs:simpleType name="gradeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="novice" />
			<xs:enumeration value="juvenile" />
			<xs:enumeration value="1" />
			<xs:enumeration value="2" />
			<xs:enumeration value="3" />
			<xs:enumeration value="4" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="eType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="MSR" />
			<xs:enumeration value="Medley" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="cidType">
		<xs:restriction base="xs:ID">
		   <xs:pattern value="c\d(4)" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="srcType">
		<xs:restriction base="xs:string">
		   <xs:pattern value="[a-zA-Z0-9]+.png" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:element name="logo">
		<xs:complexType>
		   <xs:attribute ref="source" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="name">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
				   <xs:attribute ref="grade" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="event">
		<xs:complexType>
			<xs:sequence>
			   <xs:element ref="tune" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute ref="type" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="competition">
		<xs:complexType>
			<xs:sequence>
			   <xs:element ref="event" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="band">
		<xs:complexType>
			<xs:sequence>
			   <xs:element ref="name" />
			   <xs:element ref="city" />
			   <xs:element ref="logo" minOccurs="0"/>
			   <xs:element ref="competition" />
			</xs:sequence>
			<xs:attribute ref="cid" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="bands">
		<xs:complexType>
			<xs:sequence>
			   <xs:element ref="band" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== theKevatron/Archive/XML/Lab 3/Case 2/mdpba.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!--
   New Perspectives on XML
   Tutorial 3
   Case Problem 2
   MDPBA Competition Roster
   Filename:         mdpba.xml
   Supporting Files: mdpba.xsd
-->

<bands xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				 xsi:noNamespaceSchemaLocation="mdpba.xsd">
   <band cid="c0001">
      <name grade="juvenille">School of Celtic Bagpipes &amp; Drumming</name>
      <city>Delafield</city>
      <logo source="celtic.png" />
      <competition>
         <event type="MSR">
            <tune>Charlie's Welcome</tune>
            <tune>Mrs MacPherson of Inveran</tune>
            <tune>Brown Haired Maiden</tune>
         </event>
         <event type="Medley">
            <tune>Rowd's Hornpipe</tune>
         </event>
      </competition>
   </band>
   <band cid="c0002">
      <name grade="juvenille">Badger Pipes and Drums</name>
      <city>Madison</city>
      <logo source="badger.png" />
      <competition>
         <event type="MSR">
            <tune>Lord Alexander Kennedy</tune>
            <tune>Bob of Fettercairn</tune>
            <tune>Brown Haired Maiden</tune>
         </event>
         <event type="Medley">
            <tune>Out of the Air</tune>
         </event>
      </competition>
   </band>
   <band cid="c0003">
      <name grade="juvenille">Pardeeville School of Piping and Drumming</name>
      <city>Pardeeville</city>
      <competition>
         <event type="MSR">
            <tune>Lord Alexander Kennedy</tune>
            <tune>Bob of Fettercairn</tune>
            <tune>The Little Cascade</tune>
         </event>
         <event type="Medley">
            <tune>The Radar Racketeer</tune>
         </event>
      </competition>
   </band>
   <band cid="c0004">
      <name grade="1">Zoar Scottish Pipe Band</name>
      <city>Zoar</city>
      <competition>
         <event type="MSR">
            <tune>Charlie's Welcome</tune>
            <tune>Mrs MacPherson of Inveran</tune>
            <tune>Major Manson</tune>
         </event>
         <event type="Medley">
            <tune>Miss Lily</tune>
         </event>
      </competition>
   </band>
   <band cid="c0005">
      <name grade="novice">Stockholm Pipe Band</name>
      <city>Stockholm</city>
      <competition>
         <event type="MSR">
            <tune>Pretty Marion</tune>
            <tune>The Sheepwife</tune>
            <tune>Brown Haired Maiden</tune>
         </event>
         <event type="Medley">
            <tune>Farewell to Erin</tune>
         </event>
      </competition>
   </band>
</bands>
